language: python
python:
  - 2.6
  - 2.7
  - 3.2
install:
  - pip install -r requirements/testing.txt -r requirements/production.txt --use-mirrors
  - python setup.py install
script:
  - python -m tls.version
  - coverage run setup.py test
  - coverage report --include="tls*"
